# Generated by Django 4.2.13 on 2025-03-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="category",
            field=models.CharField(
                choices=[
                    ("family", "Family"),
                    ("friends", "Friends"),
                    ("work", "Work"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
