# Generated by Django 4.2.13 on 2025-04-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_contact_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="contact_pictures/"
            ),
        ),
    ]
